apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: basic-example
  namespace: flink
spec:
  image: polyzos/flink-examples:latest
  flinkVersion: v1_15
  imagePullPolicy: Always
  flinkConfiguration:
    taskmanager.numberOfTaskSlots: "2"
  serviceAccount: flink
  jobManager:
    resource:
      memory: "2048m"
      cpu: 1
  taskManager:
    resource:
      memory: "2048m"
      cpu: 1
  job:
    jarURI: local:///opt/flink/flink-operator-tests-0.1.0.jar
    parallelism: 2
    upgradeMode: stateless
    entryClass: io.ipolyzos.AverageSensorReadings